### ISSUE TITLE
What's the major programming language in your field?

### ISSUE THREAD

**Issue by CreRecombinase** [CreRecombinase/intro-r-project#4]
Leave an emoji by the programming language most used in your field/discipline

**Comment by CreRecombinase** [comment]
![R](https://www.r-project.org/logo/Rlogo.png)

**Comment by CreRecombinase** [comment]
![python](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)

**Comment by CreRecombinase** [comment]
![MATLAB](https://www.cfn.group.cam.ac.uk/images/1428080879907.png)

**Comment by CreRecombinase** [comment]
![julia](https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Julia_prog_language.svg/1280px-Julia_prog_language.svg.png)

**Comment by CreRecombinase** [comment]
![SPSS](http://analyticpedia.com/wp-content/uploads/2012/04/spss-quick-book-1.jpg)

**Comment by CreRecombinase** [comment]
![Excel](http://cdn.makeuseof.com/wp-content/uploads/2015/12/Microsoft-Excel-Logo.png?x92042)

**Comment by aabiddanda** [comment]
C
